services:
  lgtm:
    image: grafana/otel-lgtm:0.11.5
    ports:
      - "${OBSERVABILITY_GRAFANA_PORT:-4300}:3000"
      - "4317"
      - "4318"
    environment:
      GF_PATHS_DATA: /data/grafana

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml:ro"
    ports:
      - "${OBSERVABILITY_OTLP_GRPC_PORT:-4317}:4317"
      - "${OBSERVABILITY_OTLP_HTTP_PORT:-4318}:4318"
    depends_on:
      - lgtm
